"""make guest buffet optional

Revision ID: 3a3136b47429
Revises: 5257db88014b
Create Date: 2026-07-24 10:52:36.026082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3136b47429'
down_revision: Union[str, Sequence[str], None] = '5257db88014b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'buffet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('gen_random_uuid()::text'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.alter_column('guests', 'buffet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
