"""add timestamps to models

Revision ID: 5257db88014b
Revises: 5b1c9df6a462
Create Date: 2026-07-23 13:50:22.058935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5257db88014b'
down_revision: Union[str, Sequence[str], None] = '5b1c9df6a462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buffets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('dining_sessions', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('uq_dining_sessions_active_table', 'dining_sessions', ['table_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.add_column('guests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('menu_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('menu_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('payments', sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('restaurant_tables', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('restaurant_tables', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('gen_random_uuid()::text'),
               existing_nullable=False)
    op.add_column('service_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('service_requests', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('stations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'created_at')
    op.drop_column('stations', 'updated_at')
    op.drop_column('stations', 'created_at')
    op.drop_column('service_requests', 'resolved_at')
    op.drop_column('service_requests', 'updated_at')
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.drop_column('restaurant_tables', 'updated_at')
    op.drop_column('restaurant_tables', 'created_at')
    op.drop_column('payments', 'paid_at')
    op.drop_column('order_items', 'created_at')
    op.drop_column('menu_items', 'updated_at')
    op.drop_column('menu_items', 'created_at')
    op.drop_column('guests', 'created_at')
    op.drop_index('uq_dining_sessions_active_table', table_name='dining_sessions', postgresql_where=sa.text('is_active = true'))
    op.drop_column('dining_sessions', 'approved_at')
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('buffets', 'updated_at')
    # ### end Alembic commands ###
