"""ensure one active dining session per table

Revision ID: 5b1c9df6a462
Revises: a1249b89c2c1
Create Date: 2026-07-23 09:24:47.273808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1c9df6a462'
down_revision: Union[str, Sequence[str], None] = 'a1249b89c2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_dining_sessions_active_table",
        "dining_sessions",
        ["table_id"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_dining_sessions_active_table",
        table_name="dining_sessions",
    )
    # ### end Alembic commands ###
