"""move station from menu items to categories

Revision ID: 5c1a24815d68
Revises: b703a51d391b
Create Date: 2026-07-27 10:57:46.827361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1a24815d68'
down_revision: Union[str, Sequence[str], None] = 'b703a51d391b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('station_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_categories_station_id'), 'categories', ['station_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'stations', ['station_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_menu_items_station_id'), table_name='menu_items')
    op.drop_constraint(op.f('menu_items_station_id_fkey'), 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'station_id')
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('gen_random_uuid()::text'),
               existing_nullable=False)
    op.add_column('tag_items', sa.Column('menu_item_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('tag_items_item_id_fkey'), 'tag_items', type_='foreignkey')
    op.create_foreign_key(None, 'tag_items', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tag_items', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tag_items', type_='foreignkey')
    op.create_foreign_key(op.f('tag_items_item_id_fkey'), 'tag_items', 'menu_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tag_items', 'menu_item_id')
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.add_column('menu_items', sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('menu_items_station_id_fkey'), 'menu_items', 'stations', ['station_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_menu_items_station_id'), 'menu_items', ['station_id'], unique=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_station_id'), table_name='categories')
    op.drop_column('categories', 'station_id')
    # ### end Alembic commands ###
