"""add public code to restaurant tables

Revision ID: a1249b89c2c1
Revises: 1eb470f1d712
Create Date: 2026-07-22 14:36:52.075627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1249b89c2c1'
down_revision: Union[str, Sequence[str], None] = '1eb470f1d712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_tables', sa.Column('public_code', sa.String(length=36), server_default=sa.text('gen_random_uuid()::text'), nullable=False))
    op.create_index(op.f('ix_restaurant_tables_public_code'), 'restaurant_tables', ['public_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_tables_public_code'), table_name='restaurant_tables')
    op.drop_column('restaurant_tables', 'public_code')
    # ### end Alembic commands ###
