"""add alias to tables

Revision ID: b703a51d391b
Revises: 3a3136b47429
Create Date: 2026-07-27 09:18:06.986952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b703a51d391b'
down_revision: Union[str, Sequence[str], None] = '3a3136b47429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buffets', sa.Column('alias', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_buffets_alias'), 'buffets', ['alias'], unique=True)
    op.add_column('categories', sa.Column('alias', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_categories_alias'), 'categories', ['alias'], unique=True)
    op.add_column('menu_items', sa.Column('alias', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_menu_items_alias'), 'menu_items', ['alias'], unique=True)
    op.add_column('order_item_statuses', sa.Column('alias', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_order_item_statuses_alias'), 'order_item_statuses', ['alias'], unique=True)
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('gen_random_uuid()::text'),
               existing_nullable=False)
    op.add_column('service_requests_statuses', sa.Column('alias', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_service_requests_statuses_alias'), 'service_requests_statuses', ['alias'], unique=True)
    op.add_column('staff_roles', sa.Column('alias', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_staff_roles_alias'), 'staff_roles', ['alias'], unique=True)
    op.add_column('stations', sa.Column('alias', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_stations_alias'), 'stations', ['alias'], unique=True)
    op.add_column('tags', sa.Column('alias', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_tags_alias'), 'tags', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_alias'), table_name='tags')
    op.drop_column('tags', 'alias')
    op.drop_index(op.f('ix_stations_alias'), table_name='stations')
    op.drop_column('stations', 'alias')
    op.drop_index(op.f('ix_staff_roles_alias'), table_name='staff_roles')
    op.drop_column('staff_roles', 'alias')
    op.drop_index(op.f('ix_service_requests_statuses_alias'), table_name='service_requests_statuses')
    op.drop_column('service_requests_statuses', 'alias')
    op.alter_column('restaurant_tables', 'public_code',
               existing_type=sa.VARCHAR(length=36),
               server_default=sa.text('(gen_random_uuid())::text'),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_item_statuses_alias'), table_name='order_item_statuses')
    op.drop_column('order_item_statuses', 'alias')
    op.drop_index(op.f('ix_menu_items_alias'), table_name='menu_items')
    op.drop_column('menu_items', 'alias')
    op.drop_index(op.f('ix_categories_alias'), table_name='categories')
    op.drop_column('categories', 'alias')
    op.drop_index(op.f('ix_buffets_alias'), table_name='buffets')
    op.drop_column('buffets', 'alias')
    # ### end Alembic commands ###
